/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BasicChatRouteImport } from './routes/basic-chat'
import { Route as PersistenceRouteImport } from './routes/persistence'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as StructuredOutputRouteImport } from './routes/structured-output'
import { Route as VercelAiStreamingRouteImport } from './routes/vercel-ai-streaming'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicChatRoute = BasicChatRouteImport.update({
  id: '/basic-chat',
  path: '/basic-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PersistenceRoute = PersistenceRouteImport.update({
  id: '/persistence',
  path: '/persistence',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuredOutputRoute = StructuredOutputRouteImport.update({
  id: '/structured-output',
  path: '/structured-output',
  getParentRoute: () => rootRouteImport,
} as any)
const VercelAiStreamingRoute = VercelAiStreamingRouteImport.update({
  id: '/vercel-ai-streaming',
  path: '/vercel-ai-streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-chat': typeof BasicChatRoute
  '/persistence': typeof PersistenceRoute
  '/streaming': typeof StreamingRoute
  '/structured-output': typeof StructuredOutputRoute
  '/vercel-ai-streaming': typeof VercelAiStreamingRoute
  '/api/ai/chat': typeof ApiAiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-chat': typeof BasicChatRoute
  '/persistence': typeof PersistenceRoute
  '/streaming': typeof StreamingRoute
  '/structured-output': typeof StructuredOutputRoute
  '/vercel-ai-streaming': typeof VercelAiStreamingRoute
  '/api/ai/chat': typeof ApiAiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basic-chat': typeof BasicChatRoute
  '/persistence': typeof PersistenceRoute
  '/streaming': typeof StreamingRoute
  '/structured-output': typeof StructuredOutputRoute
  '/vercel-ai-streaming': typeof VercelAiStreamingRoute
  '/api/ai/chat': typeof ApiAiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basic-chat'
    | '/persistence'
    | '/streaming'
    | '/structured-output'
    | '/vercel-ai-streaming'
    | '/api/ai/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basic-chat'
    | '/persistence'
    | '/streaming'
    | '/structured-output'
    | '/vercel-ai-streaming'
    | '/api/ai/chat'
  id:
    | '__root__'
    | '/'
    | '/basic-chat'
    | '/persistence'
    | '/streaming'
    | '/structured-output'
    | '/vercel-ai-streaming'
    | '/api/ai/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicChatRoute: typeof BasicChatRoute
  PersistenceRoute: typeof PersistenceRoute
  StreamingRoute: typeof StreamingRoute
  StructuredOutputRoute: typeof StructuredOutputRoute
  VercelAiStreamingRoute: typeof VercelAiStreamingRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-chat': {
      id: '/basic-chat'
      path: '/basic-chat'
      fullPath: '/basic-chat'
      preLoaderRoute: typeof BasicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persistence': {
      id: '/persistence'
      path: '/persistence'
      fullPath: '/persistence'
      preLoaderRoute: typeof PersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structured-output': {
      id: '/structured-output'
      path: '/structured-output'
      fullPath: '/structured-output'
      preLoaderRoute: typeof StructuredOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vercel-ai-streaming': {
      id: '/vercel-ai-streaming'
      path: '/vercel-ai-streaming'
      fullPath: '/vercel-ai-streaming'
      preLoaderRoute: typeof VercelAiStreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicChatRoute: BasicChatRoute,
  PersistenceRoute: PersistenceRoute,
  StreamingRoute: StreamingRoute,
  StructuredOutputRoute: StructuredOutputRoute,
  VercelAiStreamingRoute: VercelAiStreamingRoute,
  ApiAiChatRoute: ApiAiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
