/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BasicChatRouteImport } from './routes/basic-chat'
import { Route as BasicChatWithPersistenceRouteImport } from './routes/basic-chat-with-persistence'
import { Route as BasicChatWithPersistenceAndResumabilityRouteImport } from './routes/basic-chat-with-persistence-and-resumability'
import { Route as NonStreamingChatRouteImport } from './routes/non-streaming-chat'
import { Route as StructuredOutputRouteImport } from './routes/structured-output'
import { Route as PersistenceIndexRouteImport } from './routes/persistence/index'
import { Route as PersistenceIdRouteImport } from './routes/persistence/$id'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAiChatNoStreamingRouteImport } from './routes/api/ai/chat-no-streaming'
import { Route as ApiAiChatWithPersistenceRouteImport } from './routes/api/ai/chat-with-persistence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicChatRoute = BasicChatRouteImport.update({
  id: '/basic-chat',
  path: '/basic-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicChatWithPersistenceRoute =
  BasicChatWithPersistenceRouteImport.update({
    id: '/basic-chat-with-persistence',
    path: '/basic-chat-with-persistence',
    getParentRoute: () => rootRouteImport,
  } as any)
const BasicChatWithPersistenceAndResumabilityRoute =
  BasicChatWithPersistenceAndResumabilityRouteImport.update({
    id: '/basic-chat-with-persistence-and-resumability',
    path: '/basic-chat-with-persistence-and-resumability',
    getParentRoute: () => rootRouteImport,
  } as any)
const NonStreamingChatRoute = NonStreamingChatRouteImport.update({
  id: '/non-streaming-chat',
  path: '/non-streaming-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuredOutputRoute = StructuredOutputRouteImport.update({
  id: '/structured-output',
  path: '/structured-output',
  getParentRoute: () => rootRouteImport,
} as any)
const PersistenceIndexRoute = PersistenceIndexRouteImport.update({
  id: '/persistence/',
  path: '/persistence/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersistenceIdRoute = PersistenceIdRouteImport.update({
  id: '/persistence/$id',
  path: '/persistence/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatNoStreamingRoute = ApiAiChatNoStreamingRouteImport.update({
  id: '/api/ai/chat-no-streaming',
  path: '/api/ai/chat-no-streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatWithPersistenceRoute =
  ApiAiChatWithPersistenceRouteImport.update({
    id: '/api/ai/chat-with-persistence',
    path: '/api/ai/chat-with-persistence',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-chat': typeof BasicChatRoute
  '/basic-chat-with-persistence': typeof BasicChatWithPersistenceRoute
  '/basic-chat-with-persistence-and-resumability': typeof BasicChatWithPersistenceAndResumabilityRoute
  '/non-streaming-chat': typeof NonStreamingChatRoute
  '/structured-output': typeof StructuredOutputRoute
  '/persistence/$id': typeof PersistenceIdRoute
  '/persistence/': typeof PersistenceIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/chat-no-streaming': typeof ApiAiChatNoStreamingRoute
  '/api/ai/chat-with-persistence': typeof ApiAiChatWithPersistenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-chat': typeof BasicChatRoute
  '/basic-chat-with-persistence': typeof BasicChatWithPersistenceRoute
  '/basic-chat-with-persistence-and-resumability': typeof BasicChatWithPersistenceAndResumabilityRoute
  '/non-streaming-chat': typeof NonStreamingChatRoute
  '/structured-output': typeof StructuredOutputRoute
  '/persistence/$id': typeof PersistenceIdRoute
  '/persistence': typeof PersistenceIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/chat-no-streaming': typeof ApiAiChatNoStreamingRoute
  '/api/ai/chat-with-persistence': typeof ApiAiChatWithPersistenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basic-chat': typeof BasicChatRoute
  '/basic-chat-with-persistence': typeof BasicChatWithPersistenceRoute
  '/basic-chat-with-persistence-and-resumability': typeof BasicChatWithPersistenceAndResumabilityRoute
  '/non-streaming-chat': typeof NonStreamingChatRoute
  '/structured-output': typeof StructuredOutputRoute
  '/persistence/$id': typeof PersistenceIdRoute
  '/persistence/': typeof PersistenceIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/chat-no-streaming': typeof ApiAiChatNoStreamingRoute
  '/api/ai/chat-with-persistence': typeof ApiAiChatWithPersistenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basic-chat'
    | '/basic-chat-with-persistence'
    | '/basic-chat-with-persistence-and-resumability'
    | '/non-streaming-chat'
    | '/structured-output'
    | '/persistence/$id'
    | '/persistence/'
    | '/api/ai/chat'
    | '/api/ai/chat-no-streaming'
    | '/api/ai/chat-with-persistence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basic-chat'
    | '/basic-chat-with-persistence'
    | '/basic-chat-with-persistence-and-resumability'
    | '/non-streaming-chat'
    | '/structured-output'
    | '/persistence/$id'
    | '/persistence'
    | '/api/ai/chat'
    | '/api/ai/chat-no-streaming'
    | '/api/ai/chat-with-persistence'
  id:
    | '__root__'
    | '/'
    | '/basic-chat'
    | '/basic-chat-with-persistence'
    | '/basic-chat-with-persistence-and-resumability'
    | '/non-streaming-chat'
    | '/structured-output'
    | '/persistence/$id'
    | '/persistence/'
    | '/api/ai/chat'
    | '/api/ai/chat-no-streaming'
    | '/api/ai/chat-with-persistence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicChatRoute: typeof BasicChatRoute
  BasicChatWithPersistenceRoute: typeof BasicChatWithPersistenceRoute
  BasicChatWithPersistenceAndResumabilityRoute: typeof BasicChatWithPersistenceAndResumabilityRoute
  NonStreamingChatRoute: typeof NonStreamingChatRoute
  StructuredOutputRoute: typeof StructuredOutputRoute
  PersistenceIdRoute: typeof PersistenceIdRoute
  PersistenceIndexRoute: typeof PersistenceIndexRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiChatNoStreamingRoute: typeof ApiAiChatNoStreamingRoute
  ApiAiChatWithPersistenceRoute: typeof ApiAiChatWithPersistenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-chat': {
      id: '/basic-chat'
      path: '/basic-chat'
      fullPath: '/basic-chat'
      preLoaderRoute: typeof BasicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-chat-with-persistence': {
      id: '/basic-chat-with-persistence'
      path: '/basic-chat-with-persistence'
      fullPath: '/basic-chat-with-persistence'
      preLoaderRoute: typeof BasicChatWithPersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-chat-with-persistence-and-resumability': {
      id: '/basic-chat-with-persistence-and-resumability'
      path: '/basic-chat-with-persistence-and-resumability'
      fullPath: '/basic-chat-with-persistence-and-resumability'
      preLoaderRoute: typeof BasicChatWithPersistenceAndResumabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-streaming-chat': {
      id: '/non-streaming-chat'
      path: '/non-streaming-chat'
      fullPath: '/non-streaming-chat'
      preLoaderRoute: typeof NonStreamingChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structured-output': {
      id: '/structured-output'
      path: '/structured-output'
      fullPath: '/structured-output'
      preLoaderRoute: typeof StructuredOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persistence/': {
      id: '/persistence/'
      path: '/persistence'
      fullPath: '/persistence/'
      preLoaderRoute: typeof PersistenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persistence/$id': {
      id: '/persistence/$id'
      path: '/persistence/$id'
      fullPath: '/persistence/$id'
      preLoaderRoute: typeof PersistenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat-no-streaming': {
      id: '/api/ai/chat-no-streaming'
      path: '/api/ai/chat-no-streaming'
      fullPath: '/api/ai/chat-no-streaming'
      preLoaderRoute: typeof ApiAiChatNoStreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat-with-persistence': {
      id: '/api/ai/chat-with-persistence'
      path: '/api/ai/chat-with-persistence'
      fullPath: '/api/ai/chat-with-persistence'
      preLoaderRoute: typeof ApiAiChatWithPersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicChatRoute: BasicChatRoute,
  BasicChatWithPersistenceRoute: BasicChatWithPersistenceRoute,
  BasicChatWithPersistenceAndResumabilityRoute:
    BasicChatWithPersistenceAndResumabilityRoute,
  NonStreamingChatRoute: NonStreamingChatRoute,
  StructuredOutputRoute: StructuredOutputRoute,
  PersistenceIdRoute: PersistenceIdRoute,
  PersistenceIndexRoute: PersistenceIndexRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiChatNoStreamingRoute: ApiAiChatNoStreamingRoute,
  ApiAiChatWithPersistenceRoute: ApiAiChatWithPersistenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
