/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BasicChatRouteImport } from './routes/basic-chat'
import { Route as BasicChatStreamingRouteImport } from './routes/basic-chat-streaming'
import { Route as BasicChatWithPersistenceRouteImport } from './routes/basic-chat-with-persistence'
import { Route as StructuredOutputRouteImport } from './routes/structured-output'
import { Route as ApiAiChatNoStreamingRouteImport } from './routes/api/ai/chat-no-streaming'
import { Route as ApiAiChatStreamingRouteImport } from './routes/api/ai/chat-streaming'
import { Route as ApiAiChatStructuredOutputRouteImport } from './routes/api/ai/chat-structured-output'
import { Route as ApiAiChatWithPersistenceRouteImport } from './routes/api/ai/chat-with-persistence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicChatRoute = BasicChatRouteImport.update({
  id: '/basic-chat',
  path: '/basic-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicChatStreamingRoute = BasicChatStreamingRouteImport.update({
  id: '/basic-chat-streaming',
  path: '/basic-chat-streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicChatWithPersistenceRoute =
  BasicChatWithPersistenceRouteImport.update({
    id: '/basic-chat-with-persistence',
    path: '/basic-chat-with-persistence',
    getParentRoute: () => rootRouteImport,
  } as any)
const StructuredOutputRoute = StructuredOutputRouteImport.update({
  id: '/structured-output',
  path: '/structured-output',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatNoStreamingRoute = ApiAiChatNoStreamingRouteImport.update({
  id: '/api/ai/chat-no-streaming',
  path: '/api/ai/chat-no-streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatStreamingRoute = ApiAiChatStreamingRouteImport.update({
  id: '/api/ai/chat-streaming',
  path: '/api/ai/chat-streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatStructuredOutputRoute =
  ApiAiChatStructuredOutputRouteImport.update({
    id: '/api/ai/chat-structured-output',
    path: '/api/ai/chat-structured-output',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiChatWithPersistenceRoute =
  ApiAiChatWithPersistenceRouteImport.update({
    id: '/api/ai/chat-with-persistence',
    path: '/api/ai/chat-with-persistence',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basic-chat': typeof BasicChatRoute
  '/basic-chat-streaming': typeof BasicChatStreamingRoute
  '/basic-chat-with-persistence': typeof BasicChatWithPersistenceRoute
  '/structured-output': typeof StructuredOutputRoute
  '/api/ai/chat-no-streaming': typeof ApiAiChatNoStreamingRoute
  '/api/ai/chat-streaming': typeof ApiAiChatStreamingRoute
  '/api/ai/chat-structured-output': typeof ApiAiChatStructuredOutputRoute
  '/api/ai/chat-with-persistence': typeof ApiAiChatWithPersistenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basic-chat': typeof BasicChatRoute
  '/basic-chat-streaming': typeof BasicChatStreamingRoute
  '/basic-chat-with-persistence': typeof BasicChatWithPersistenceRoute
  '/structured-output': typeof StructuredOutputRoute
  '/api/ai/chat-no-streaming': typeof ApiAiChatNoStreamingRoute
  '/api/ai/chat-streaming': typeof ApiAiChatStreamingRoute
  '/api/ai/chat-structured-output': typeof ApiAiChatStructuredOutputRoute
  '/api/ai/chat-with-persistence': typeof ApiAiChatWithPersistenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basic-chat': typeof BasicChatRoute
  '/basic-chat-streaming': typeof BasicChatStreamingRoute
  '/basic-chat-with-persistence': typeof BasicChatWithPersistenceRoute
  '/structured-output': typeof StructuredOutputRoute
  '/api/ai/chat-no-streaming': typeof ApiAiChatNoStreamingRoute
  '/api/ai/chat-streaming': typeof ApiAiChatStreamingRoute
  '/api/ai/chat-structured-output': typeof ApiAiChatStructuredOutputRoute
  '/api/ai/chat-with-persistence': typeof ApiAiChatWithPersistenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basic-chat'
    | '/basic-chat-streaming'
    | '/basic-chat-with-persistence'
    | '/structured-output'
    | '/api/ai/chat-no-streaming'
    | '/api/ai/chat-streaming'
    | '/api/ai/chat-structured-output'
    | '/api/ai/chat-with-persistence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basic-chat'
    | '/basic-chat-streaming'
    | '/basic-chat-with-persistence'
    | '/structured-output'
    | '/api/ai/chat-no-streaming'
    | '/api/ai/chat-streaming'
    | '/api/ai/chat-structured-output'
    | '/api/ai/chat-with-persistence'
  id:
    | '__root__'
    | '/'
    | '/basic-chat'
    | '/basic-chat-streaming'
    | '/basic-chat-with-persistence'
    | '/structured-output'
    | '/api/ai/chat-no-streaming'
    | '/api/ai/chat-streaming'
    | '/api/ai/chat-structured-output'
    | '/api/ai/chat-with-persistence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasicChatRoute: typeof BasicChatRoute
  BasicChatStreamingRoute: typeof BasicChatStreamingRoute
  BasicChatWithPersistenceRoute: typeof BasicChatWithPersistenceRoute
  StructuredOutputRoute: typeof StructuredOutputRoute
  ApiAiChatNoStreamingRoute: typeof ApiAiChatNoStreamingRoute
  ApiAiChatStreamingRoute: typeof ApiAiChatStreamingRoute
  ApiAiChatStructuredOutputRoute: typeof ApiAiChatStructuredOutputRoute
  ApiAiChatWithPersistenceRoute: typeof ApiAiChatWithPersistenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-chat': {
      id: '/basic-chat'
      path: '/basic-chat'
      fullPath: '/basic-chat'
      preLoaderRoute: typeof BasicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-chat-streaming': {
      id: '/basic-chat-streaming'
      path: '/basic-chat-streaming'
      fullPath: '/basic-chat-streaming'
      preLoaderRoute: typeof BasicChatStreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-chat-with-persistence': {
      id: '/basic-chat-with-persistence'
      path: '/basic-chat-with-persistence'
      fullPath: '/basic-chat-with-persistence'
      preLoaderRoute: typeof BasicChatWithPersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structured-output': {
      id: '/structured-output'
      path: '/structured-output'
      fullPath: '/structured-output'
      preLoaderRoute: typeof StructuredOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat-no-streaming': {
      id: '/api/ai/chat-no-streaming'
      path: '/api/ai/chat-no-streaming'
      fullPath: '/api/ai/chat-no-streaming'
      preLoaderRoute: typeof ApiAiChatNoStreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat-streaming': {
      id: '/api/ai/chat-streaming'
      path: '/api/ai/chat-streaming'
      fullPath: '/api/ai/chat-streaming'
      preLoaderRoute: typeof ApiAiChatStreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat-structured-output': {
      id: '/api/ai/chat-structured-output'
      path: '/api/ai/chat-structured-output'
      fullPath: '/api/ai/chat-structured-output'
      preLoaderRoute: typeof ApiAiChatStructuredOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat-with-persistence': {
      id: '/api/ai/chat-with-persistence'
      path: '/api/ai/chat-with-persistence'
      fullPath: '/api/ai/chat-with-persistence'
      preLoaderRoute: typeof ApiAiChatWithPersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasicChatRoute: BasicChatRoute,
  BasicChatStreamingRoute: BasicChatStreamingRoute,
  BasicChatWithPersistenceRoute: BasicChatWithPersistenceRoute,
  StructuredOutputRoute: StructuredOutputRoute,
  ApiAiChatNoStreamingRoute: ApiAiChatNoStreamingRoute,
  ApiAiChatStreamingRoute: ApiAiChatStreamingRoute,
  ApiAiChatStructuredOutputRoute: ApiAiChatStructuredOutputRoute,
  ApiAiChatWithPersistenceRoute: ApiAiChatWithPersistenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
